os: Windows Server 2012
init:
  - git config --global core.autocrlf input
install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\sbt" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'https://github.com/sbt/sbt/releases/download/v1.3.3/sbt-1.3.3.zip',
          'C:\sbt-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\sbt-bin.zip", "C:\sbt")
      }
  - cmd: SET PATH=C:\sbt\sbt\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET SBT_OPTS=-Dsbt.supershell=false
build_script:
  - sbt -batch clean +compile < /dev/null
test_script:
  - sbt -batch +test +mimaReportBinaryIssues < /dev/null
